import { Inter } from "next/font/google";
import "./globals.css";
import News from "@/components/News";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between max-w-6xl mx-auto">
          <div>
            <News />
          </div>
          <div>{children}</div>
          <div>
            <Sidebar />
          </div>
        </div>
      </body>
    </html>
  );
}
